// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc3t0wFaio6c0JL5ZlUAOBoBJzxu83wfs',
    appId: '1:634032719081:web:77f27d091d64a60e0a5c78',
    messagingSenderId: '634032719081',
    projectId: 'crud-2403f1',
    authDomain: 'crud-2403f1.firebaseapp.com',
    databaseURL: 'https://crud-2403f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-2403f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLa7Rugoob3qP8mdGerdsQjBaYlJBUAV4',
    appId: '1:634032719081:android:b0fccab2bdc6c2f70a5c78',
    messagingSenderId: '634032719081',
    projectId: 'crud-2403f1',
    databaseURL: 'https://crud-2403f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-2403f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFaFg1BKi6PU_6CMGYTqZUfMapvrUxogY',
    appId: '1:634032719081:ios:ae756d294af633c60a5c78',
    messagingSenderId: '634032719081',
    projectId: 'crud-2403f1',
    databaseURL: 'https://crud-2403f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-2403f1.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );
}
