// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtby5g3yIA13UnCXy1aIpm_cLNejdcmJw',
    appId: '1:770288497466:web:0bd96e487284a445c01603',
    messagingSenderId: '770288497466',
    projectId: 'flutter-crud-5544f',
    authDomain: 'flutter-crud-5544f.firebaseapp.com',
    storageBucket: 'flutter-crud-5544f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6Kscn8rWUoOX2_LsLvL8iCRPFn2S8ac',
    appId: '1:770288497466:android:9357fd6b85332cd2c01603',
    messagingSenderId: '770288497466',
    projectId: 'flutter-crud-5544f',
    storageBucket: 'flutter-crud-5544f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjQx3qu8MQ5GB0M_8_J3l8q6HzMKZtnns',
    appId: '1:770288497466:ios:dfded441c3ec3cb7c01603',
    messagingSenderId: '770288497466',
    projectId: 'flutter-crud-5544f',
    storageBucket: 'flutter-crud-5544f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
